name: TwithcLib.Extension CI
on:
  # Triggers the workflow on push events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-deploy:
    name: Build and Deploy NuGet package
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Configure our dotnet environments
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: | 
            3.1.x
            5.0.x
            
      # Configure our nuget environment
      - name: Configure NuGet
        uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NuGetAPIKey }}
          nuget-version: '5.x'
  
      # Build and pack Nuget packages
      - name: Build NuGet packages
        run: |
          dotnet build
          dotnet pack --output bin/
          
      # Deploy our packages to Nuget.org
      - name: Deploy NuGet packages (Nuget.org)
        run: |
          cd bin/
          dotnet nuget push "*.nupkg" --api-key ${{ secrets.NuGetAPIKey }} --source https://api.nuget.org/v3/index.json --skip-duplicate
